// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import DropDownController from "./dropDown_controller"
application.register("dropDown", DropDownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import StyleLabelsController from "./style_labels_controller"
application.register("style-labels", StyleLabelsController)
