detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  TooManyInstanceVariables:
    exclude:
      - GiftsController

exclude_paths:
  - db/migrate
