detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  TooManyInstanceVariables:
    exclude:
      - GiftsController

  TooManyStatements:
    exclude:
      - PurchaseController
exclude_paths:
  - db/migrate
