detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

exclude_paths:
  - db/migrate
  - app/controllers/gifts_controller.rb
